default_context:
  project_name: 'TOAuth'
  project_slug: 'toauth'
  domain_main: 'toauth.com'
  domain_staging: 'stag.toauth.com'
  docker_swarm_stack_name_main: 'toauth-com'
  docker_swarm_stack_name_staging: 'stag-toauth-com'
  secret_key: '23fc2ab2f7662025cfb076701894aee771c2a5734f66afbc16f6157350f0f408'
  first_superuser: 'admin@toauth.com'
  first_superuser_password: 'admin123'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.toauth.com", "https://stag.toauth.com", "https://toauth.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@toauth.com'
  postgres_password: 'admin123'
  pgadmin_default_user: 'admin@toauth.com'
  pgadmin_default_user_password: 'admin123'
  traefik_constraint_tag: 'toauth.com'
  traefik_constraint_tag_staging: 'stag.toauth.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:admin123'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
